<?php

  // include base peer class
  require_once 'src/model/whiteboard/om/BaseElementPeer.php';

  // include object class
  include_once 'src/model/whiteboard/Element.php';


/**
 * Skeleton subclass for performing query and update operations on the 'element' table.
 *
 * Element Table
 *
 * This class was autogenerated by Propel on:
 *
 * 02/15/13 21:36:52
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    src/model/whiteboard
 */
class ElementPeer extends BaseElementPeer {

} // ElementPeer
