<?php

  // include base peer class
  require_once 'src/model/whiteboard/om/BasePermissionPeer.php';

  // include object class
  include_once 'src/model/whiteboard/Permission.php';


/**
 * Skeleton subclass for performing query and update operations on the 'permission' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * 02/15/13 21:36:52
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    src/model/whiteboard
 */
class PermissionPeer extends BasePermissionPeer {

} // PermissionPeer
