<?php

require_once 'src/model/whiteboard/om/BasePermission.php';


/**
 * Skeleton subclass for representing a row from the 'permission' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * 02/15/13 21:36:52
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    src/model/whiteboard
 */
class Permission extends BasePermission {

} // Permission
