<?php

require_once 'propel/map/MapBuilder.php';
include_once 'creole/CreoleTypes.php';


/**
 * This class adds structure of 'element' table to 'whiteboard' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel on:
 *
 * 02/15/13 21:36:52
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    src/model/whiteboard.map
 */
class ElementMapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'src/model/whiteboard.map.ElementMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap('whiteboard');

		$tMap = $this->dbMap->addTable('element');
		$tMap->setPhpName('Element');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ELEMENT_ID', 'ElementId', 'int', CreoleTypes::INTEGER, true, null);

		$tMap->addColumn('VALUE', 'Value', 'string', CreoleTypes::LONGVARCHAR, false, null);

		$tMap->addColumn('ID', 'Id', 'string', CreoleTypes::VARCHAR, false, 10);

		$tMap->addColumn('TABINDEX', 'Tabindex', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('CSS_TOP', 'CssTop', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('CSS_LEFT', 'CssLeft', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('CSS_WIDTH', 'CssWidth', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('CSS_HEIGHT', 'CssHeight', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('ROTATION', 'Rotation', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addColumn('LAST_CHANGE_BY', 'LastChangeBy', 'int', CreoleTypes::INTEGER, false, null);

		$tMap->addForeignKey('PRODUCTION_ID', 'ProductionId', 'int', CreoleTypes::INTEGER, 'production', 'PRODUCTION_ID', false, 10);

	} // doBuild()

} // ElementMapBuilder
