<?php

require_once 'propel/om/BaseObject.php';

require_once 'propel/om/Persistent.php';


include_once 'propel/util/Criteria.php';

include_once 'src/model/whiteboard/ProductionPeer.php';

/**
 * Base class that represents a row from the 'production' table.
 *
 * Production Table
 *
 * This class was autogenerated by Propel on:
 *
 * 02/15/13 21:36:51
 *
 * @package    src/model/whiteboard.om
 */
abstract class BaseProduction extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ProductionPeer
	 */
	protected static $peer;


	/**
	 * The value for the production_id field.
	 * @var        int
	 */
	protected $production_id;


	/**
	 * The value for the creation_date field.
	 * @var        int
	 */
	protected $creation_date;


	/**
	 * The value for the update_date field.
	 * @var        int
	 */
	protected $update_date;


	/**
	 * The value for the room_id field.
	 * @var        int
	 */
	protected $room_id;

	/**
	 * @var        Room
	 */
	protected $aRoom;

	/**
	 * Collection to store aggregation of collElements.
	 * @var        array
	 */
	protected $collElements;

	/**
	 * The criteria used to select the current contents of collElements.
	 * @var        Criteria
	 */
	protected $lastElementCriteria = null;

	/**
	 * Collection to store aggregation of collMessages.
	 * @var        array
	 */
	protected $collMessages;

	/**
	 * The criteria used to select the current contents of collMessages.
	 * @var        Criteria
	 */
	protected $lastMessageCriteria = null;

	/**
	 * Collection to store aggregation of collHistorys.
	 * @var        array
	 */
	protected $collHistorys;

	/**
	 * The criteria used to select the current contents of collHistorys.
	 * @var        Criteria
	 */
	protected $lastHistoryCriteria = null;

	/**
	 * Collection to store aggregation of collProductionHistorys.
	 * @var        array
	 */
	protected $collProductionHistorys;

	/**
	 * The criteria used to select the current contents of collProductionHistorys.
	 * @var        Criteria
	 */
	protected $lastProductionHistoryCriteria = null;

	/**
	 * Collection to store aggregation of collOnlines.
	 * @var        array
	 */
	protected $collOnlines;

	/**
	 * The criteria used to select the current contents of collOnlines.
	 * @var        Criteria
	 */
	protected $lastOnlineCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [production_id] column value.
	 * Room id
	 * @return     int
	 */
	public function getProductionId()
	{

		return $this->production_id;
	}

	/**
	 * Get the [optionally formatted] [creation_date] column value.
	 * Creation date
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the integer unix timestamp will be returned.
	 * @return     mixed Formatted date/time value as string or integer unix timestamp (if format is NULL).
	 * @throws     PropelException - if unable to convert the date/time to timestamp.
	 */
	public function getCreationDate($format = '%d/%m/%Y')
	{

		if ($this->creation_date === null || $this->creation_date === '') {
			return null;
		} elseif (!is_int($this->creation_date)) {
			// a non-timestamp value was set externally, so we convert it
			$ts = strtotime($this->creation_date);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse value of [creation_date] as date/time value: " . var_export($this->creation_date, true));
			}
		} else {
			$ts = $this->creation_date;
		}
		if ($format === null) {
			return $ts;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $ts);
		} else {
			return date($format, $ts);
		}
	}

	/**
	 * Get the [optionally formatted] [update_date] column value.
	 * Latest update
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the integer unix timestamp will be returned.
	 * @return     mixed Formatted date/time value as string or integer unix timestamp (if format is NULL).
	 * @throws     PropelException - if unable to convert the date/time to timestamp.
	 */
	public function getUpdateDate($format = '%d/%m/%Y')
	{

		if ($this->update_date === null || $this->update_date === '') {
			return null;
		} elseif (!is_int($this->update_date)) {
			// a non-timestamp value was set externally, so we convert it
			$ts = strtotime($this->update_date);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse value of [update_date] as date/time value: " . var_export($this->update_date, true));
			}
		} else {
			$ts = $this->update_date;
		}
		if ($format === null) {
			return $ts;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $ts);
		} else {
			return date($format, $ts);
		}
	}

	/**
	 * Get the [room_id] column value.
	 * 
	 * @return     int
	 */
	public function getRoomId()
	{

		return $this->room_id;
	}

	/**
	 * Set the value of [production_id] column.
	 * Room id
	 * @param      int $v new value
	 * @return     void
	 */
	public function setProductionId($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->production_id !== $v) {
			$this->production_id = $v;
			$this->modifiedColumns[] = ProductionPeer::PRODUCTION_ID;
		}

	} // setProductionId()

	/**
	 * Set the value of [creation_date] column.
	 * Creation date
	 * @param      int $v new value
	 * @return     void
	 */
	public function setCreationDate($v)
	{

		if ($v !== null && !is_int($v)) {
			$ts = strtotime($v);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse date/time value for [creation_date] from input: " . var_export($v, true));
			}
		} else {
			$ts = $v;
		}
		if ($this->creation_date !== $ts) {
			$this->creation_date = $ts;
			$this->modifiedColumns[] = ProductionPeer::CREATION_DATE;
		}

	} // setCreationDate()

	/**
	 * Set the value of [update_date] column.
	 * Latest update
	 * @param      int $v new value
	 * @return     void
	 */
	public function setUpdateDate($v)
	{

		if ($v !== null && !is_int($v)) {
			$ts = strtotime($v);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse date/time value for [update_date] from input: " . var_export($v, true));
			}
		} else {
			$ts = $v;
		}
		if ($this->update_date !== $ts) {
			$this->update_date = $ts;
			$this->modifiedColumns[] = ProductionPeer::UPDATE_DATE;
		}

	} // setUpdateDate()

	/**
	 * Set the value of [room_id] column.
	 * 
	 * @param      int $v new value
	 * @return     void
	 */
	public function setRoomId($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->room_id !== $v) {
			$this->room_id = $v;
			$this->modifiedColumns[] = ProductionPeer::ROOM_ID;
		}

		if ($this->aRoom !== null && $this->aRoom->getRoomId() !== $v) {
			$this->aRoom = null;
		}

	} // setRoomId()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (1-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      ResultSet $rs The ResultSet class with cursor advanced to desired record pos.
	 * @param      int $startcol 1-based offset column which indicates which restultset column to start with.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate(ResultSet $rs, $startcol = 1)
	{
		try {

			$this->production_id = $rs->getInt($startcol + 0);

			$this->creation_date = $rs->getDate($startcol + 1, null);

			$this->update_date = $rs->getDate($startcol + 2, null);

			$this->room_id = $rs->getInt($startcol + 3);

			$this->resetModified();

			$this->setNew(false);

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = ProductionPeer::NUM_COLUMNS - ProductionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Production object", $e);
		}
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      Connection $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductionPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			ProductionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.  If the object is new,
	 * it inserts it; otherwise an update is performed.  This method
	 * wraps the doSave() worker method in a transaction.
	 *
	 * @param      Connection $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProductionPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			$affectedRows = $this->doSave($con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      Connection $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave($con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRoom !== null) {
				if ($this->aRoom->isModified()) {
					$affectedRows += $this->aRoom->save($con);
				}
				$this->setRoom($this->aRoom);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ProductionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setProductionId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ProductionPeer::doUpdate($this, $con);
				}
				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collElements !== null) {
				foreach($this->collElements as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMessages !== null) {
				foreach($this->collMessages as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collHistorys !== null) {
				foreach($this->collHistorys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collProductionHistorys !== null) {
				foreach($this->collProductionHistorys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collOnlines !== null) {
				foreach($this->collOnlines as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;
		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRoom !== null) {
				if (!$this->aRoom->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRoom->getValidationFailures());
				}
			}


			if (($retval = ProductionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collElements !== null) {
					foreach($this->collElements as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMessages !== null) {
					foreach($this->collMessages as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collHistorys !== null) {
					foreach($this->collHistorys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collProductionHistorys !== null) {
					foreach($this->collProductionHistorys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collOnlines !== null) {
					foreach($this->collOnlines as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ProductionPeer::DATABASE_NAME);

		if ($this->isColumnModified(ProductionPeer::PRODUCTION_ID)) $criteria->add(ProductionPeer::PRODUCTION_ID, $this->production_id);
		if ($this->isColumnModified(ProductionPeer::CREATION_DATE)) $criteria->add(ProductionPeer::CREATION_DATE, $this->creation_date);
		if ($this->isColumnModified(ProductionPeer::UPDATE_DATE)) $criteria->add(ProductionPeer::UPDATE_DATE, $this->update_date);
		if ($this->isColumnModified(ProductionPeer::ROOM_ID)) $criteria->add(ProductionPeer::ROOM_ID, $this->room_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ProductionPeer::DATABASE_NAME);

		$criteria->add(ProductionPeer::PRODUCTION_ID, $this->production_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getProductionId();
	}

	/**
	 * Generic method to set the primary key (production_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setProductionId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Production (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCreationDate($this->creation_date);

		$copyObj->setUpdateDate($this->update_date);

		$copyObj->setRoomId($this->room_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach($this->getElements() as $relObj) {
				$copyObj->addElement($relObj->copy($deepCopy));
			}

			foreach($this->getMessages() as $relObj) {
				$copyObj->addMessage($relObj->copy($deepCopy));
			}

			foreach($this->getHistorys() as $relObj) {
				$copyObj->addHistory($relObj->copy($deepCopy));
			}

			foreach($this->getProductionHistorys() as $relObj) {
				$copyObj->addProductionHistory($relObj->copy($deepCopy));
			}

			foreach($this->getOnlines() as $relObj) {
				$copyObj->addOnline($relObj->copy($deepCopy));
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setProductionId(NULL); // this is a pkey column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Production Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ProductionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ProductionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Room object.
	 *
	 * @param      Room $v
	 * @return     void
	 * @throws     PropelException
	 */
	public function setRoom($v)
	{


		if ($v === null) {
			$this->setRoomId(NULL);
		} else {
			$this->setRoomId($v->getRoomId());
		}


		$this->aRoom = $v;
	}


	/**
	 * Get the associated Room object
	 *
	 * @param      Connection Optional Connection object.
	 * @return     Room The associated Room object.
	 * @throws     PropelException
	 */
	public function getRoom($con = null)
	{
		// include the related Peer class
		include_once 'src/model/whiteboard/om/BaseRoomPeer.php';

		if ($this->aRoom === null && ($this->room_id !== null)) {

			$this->aRoom = RoomPeer::retrieveByPK($this->room_id, $con);

			/* The following can be used instead of the line above to
			   guarantee the related object contains a reference
			   to this object, but this level of coupling
			   may be undesirable in many circumstances.
			   As it can lead to a db query with many results that may
			   never be used.
			   $obj = RoomPeer::retrieveByPK($this->room_id, $con);
			   $obj->addRooms($this);
			 */
		}
		return $this->aRoom;
	}

	/**
	 * Temporary storage of collElements to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return     void
	 */
	public function initElements()
	{
		if ($this->collElements === null) {
			$this->collElements = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production has previously
	 * been saved, it will retrieve related Elements from storage.
	 * If this Production is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param      Connection $con
	 * @param      Criteria $criteria
	 * @throws     PropelException
	 */
	public function getElements($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseElementPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collElements === null) {
			if ($this->isNew()) {
			   $this->collElements = array();
			} else {

				$criteria->add(ElementPeer::PRODUCTION_ID, $this->getProductionId());

				ElementPeer::addSelectColumns($criteria);
				$this->collElements = ElementPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ElementPeer::PRODUCTION_ID, $this->getProductionId());

				ElementPeer::addSelectColumns($criteria);
				if (!isset($this->lastElementCriteria) || !$this->lastElementCriteria->equals($criteria)) {
					$this->collElements = ElementPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastElementCriteria = $criteria;
		return $this->collElements;
	}

	/**
	 * Returns the number of related Elements.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      Connection $con
	 * @throws     PropelException
	 */
	public function countElements($criteria = null, $distinct = false, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseElementPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(ElementPeer::PRODUCTION_ID, $this->getProductionId());

		return ElementPeer::doCount($criteria, $distinct, $con);
	}

	/**
	 * Method called to associate a Element object to this object
	 * through the Element foreign key attribute
	 *
	 * @param      Element $l Element
	 * @return     void
	 * @throws     PropelException
	 */
	public function addElement(Element $l)
	{
		$this->collElements[] = $l;
		$l->setProduction($this);
	}

	/**
	 * Temporary storage of collMessages to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return     void
	 */
	public function initMessages()
	{
		if ($this->collMessages === null) {
			$this->collMessages = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production has previously
	 * been saved, it will retrieve related Messages from storage.
	 * If this Production is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param      Connection $con
	 * @param      Criteria $criteria
	 * @throws     PropelException
	 */
	public function getMessages($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseMessagePeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMessages === null) {
			if ($this->isNew()) {
			   $this->collMessages = array();
			} else {

				$criteria->add(MessagePeer::PRODUCTION_ID, $this->getProductionId());

				MessagePeer::addSelectColumns($criteria);
				$this->collMessages = MessagePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MessagePeer::PRODUCTION_ID, $this->getProductionId());

				MessagePeer::addSelectColumns($criteria);
				if (!isset($this->lastMessageCriteria) || !$this->lastMessageCriteria->equals($criteria)) {
					$this->collMessages = MessagePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMessageCriteria = $criteria;
		return $this->collMessages;
	}

	/**
	 * Returns the number of related Messages.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      Connection $con
	 * @throws     PropelException
	 */
	public function countMessages($criteria = null, $distinct = false, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseMessagePeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(MessagePeer::PRODUCTION_ID, $this->getProductionId());

		return MessagePeer::doCount($criteria, $distinct, $con);
	}

	/**
	 * Method called to associate a Message object to this object
	 * through the Message foreign key attribute
	 *
	 * @param      Message $l Message
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMessage(Message $l)
	{
		$this->collMessages[] = $l;
		$l->setProduction($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production is new, it will return
	 * an empty collection; or if this Production has previously
	 * been saved, it will retrieve related Messages from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Production.
	 */
	public function getMessagesJoinUser($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseMessagePeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMessages === null) {
			if ($this->isNew()) {
				$this->collMessages = array();
			} else {

				$criteria->add(MessagePeer::PRODUCTION_ID, $this->getProductionId());

				$this->collMessages = MessagePeer::doSelectJoinUser($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MessagePeer::PRODUCTION_ID, $this->getProductionId());

			if (!isset($this->lastMessageCriteria) || !$this->lastMessageCriteria->equals($criteria)) {
				$this->collMessages = MessagePeer::doSelectJoinUser($criteria, $con);
			}
		}
		$this->lastMessageCriteria = $criteria;

		return $this->collMessages;
	}

	/**
	 * Temporary storage of collHistorys to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return     void
	 */
	public function initHistorys()
	{
		if ($this->collHistorys === null) {
			$this->collHistorys = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production has previously
	 * been saved, it will retrieve related Historys from storage.
	 * If this Production is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param      Connection $con
	 * @param      Criteria $criteria
	 * @throws     PropelException
	 */
	public function getHistorys($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseHistoryPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collHistorys === null) {
			if ($this->isNew()) {
			   $this->collHistorys = array();
			} else {

				$criteria->add(HistoryPeer::PRODUCTION_ID, $this->getProductionId());

				HistoryPeer::addSelectColumns($criteria);
				$this->collHistorys = HistoryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(HistoryPeer::PRODUCTION_ID, $this->getProductionId());

				HistoryPeer::addSelectColumns($criteria);
				if (!isset($this->lastHistoryCriteria) || !$this->lastHistoryCriteria->equals($criteria)) {
					$this->collHistorys = HistoryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastHistoryCriteria = $criteria;
		return $this->collHistorys;
	}

	/**
	 * Returns the number of related Historys.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      Connection $con
	 * @throws     PropelException
	 */
	public function countHistorys($criteria = null, $distinct = false, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseHistoryPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(HistoryPeer::PRODUCTION_ID, $this->getProductionId());

		return HistoryPeer::doCount($criteria, $distinct, $con);
	}

	/**
	 * Method called to associate a History object to this object
	 * through the History foreign key attribute
	 *
	 * @param      History $l History
	 * @return     void
	 * @throws     PropelException
	 */
	public function addHistory(History $l)
	{
		$this->collHistorys[] = $l;
		$l->setProduction($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production is new, it will return
	 * an empty collection; or if this Production has previously
	 * been saved, it will retrieve related Historys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Production.
	 */
	public function getHistorysJoinUser($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseHistoryPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collHistorys === null) {
			if ($this->isNew()) {
				$this->collHistorys = array();
			} else {

				$criteria->add(HistoryPeer::PRODUCTION_ID, $this->getProductionId());

				$this->collHistorys = HistoryPeer::doSelectJoinUser($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(HistoryPeer::PRODUCTION_ID, $this->getProductionId());

			if (!isset($this->lastHistoryCriteria) || !$this->lastHistoryCriteria->equals($criteria)) {
				$this->collHistorys = HistoryPeer::doSelectJoinUser($criteria, $con);
			}
		}
		$this->lastHistoryCriteria = $criteria;

		return $this->collHistorys;
	}

	/**
	 * Temporary storage of collProductionHistorys to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return     void
	 */
	public function initProductionHistorys()
	{
		if ($this->collProductionHistorys === null) {
			$this->collProductionHistorys = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production has previously
	 * been saved, it will retrieve related ProductionHistorys from storage.
	 * If this Production is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param      Connection $con
	 * @param      Criteria $criteria
	 * @throws     PropelException
	 */
	public function getProductionHistorys($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseProductionHistoryPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductionHistorys === null) {
			if ($this->isNew()) {
			   $this->collProductionHistorys = array();
			} else {

				$criteria->add(ProductionHistoryPeer::PRODUCTION_ID, $this->getProductionId());

				ProductionHistoryPeer::addSelectColumns($criteria);
				$this->collProductionHistorys = ProductionHistoryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProductionHistoryPeer::PRODUCTION_ID, $this->getProductionId());

				ProductionHistoryPeer::addSelectColumns($criteria);
				if (!isset($this->lastProductionHistoryCriteria) || !$this->lastProductionHistoryCriteria->equals($criteria)) {
					$this->collProductionHistorys = ProductionHistoryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProductionHistoryCriteria = $criteria;
		return $this->collProductionHistorys;
	}

	/**
	 * Returns the number of related ProductionHistorys.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      Connection $con
	 * @throws     PropelException
	 */
	public function countProductionHistorys($criteria = null, $distinct = false, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseProductionHistoryPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(ProductionHistoryPeer::PRODUCTION_ID, $this->getProductionId());

		return ProductionHistoryPeer::doCount($criteria, $distinct, $con);
	}

	/**
	 * Method called to associate a ProductionHistory object to this object
	 * through the ProductionHistory foreign key attribute
	 *
	 * @param      ProductionHistory $l ProductionHistory
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProductionHistory(ProductionHistory $l)
	{
		$this->collProductionHistorys[] = $l;
		$l->setProduction($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production is new, it will return
	 * an empty collection; or if this Production has previously
	 * been saved, it will retrieve related ProductionHistorys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Production.
	 */
	public function getProductionHistorysJoinUser($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseProductionHistoryPeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductionHistorys === null) {
			if ($this->isNew()) {
				$this->collProductionHistorys = array();
			} else {

				$criteria->add(ProductionHistoryPeer::PRODUCTION_ID, $this->getProductionId());

				$this->collProductionHistorys = ProductionHistoryPeer::doSelectJoinUser($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProductionHistoryPeer::PRODUCTION_ID, $this->getProductionId());

			if (!isset($this->lastProductionHistoryCriteria) || !$this->lastProductionHistoryCriteria->equals($criteria)) {
				$this->collProductionHistorys = ProductionHistoryPeer::doSelectJoinUser($criteria, $con);
			}
		}
		$this->lastProductionHistoryCriteria = $criteria;

		return $this->collProductionHistorys;
	}

	/**
	 * Temporary storage of collOnlines to save a possible db hit in
	 * the event objects are add to the collection, but the
	 * complete collection is never requested.
	 * @return     void
	 */
	public function initOnlines()
	{
		if ($this->collOnlines === null) {
			$this->collOnlines = array();
		}
	}

	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production has previously
	 * been saved, it will retrieve related Onlines from storage.
	 * If this Production is new, it will return
	 * an empty collection or the current collection, the criteria
	 * is ignored on a new object.
	 *
	 * @param      Connection $con
	 * @param      Criteria $criteria
	 * @throws     PropelException
	 */
	public function getOnlines($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseOnlinePeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOnlines === null) {
			if ($this->isNew()) {
			   $this->collOnlines = array();
			} else {

				$criteria->add(OnlinePeer::PRODUCTION_ID, $this->getProductionId());

				OnlinePeer::addSelectColumns($criteria);
				$this->collOnlines = OnlinePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OnlinePeer::PRODUCTION_ID, $this->getProductionId());

				OnlinePeer::addSelectColumns($criteria);
				if (!isset($this->lastOnlineCriteria) || !$this->lastOnlineCriteria->equals($criteria)) {
					$this->collOnlines = OnlinePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOnlineCriteria = $criteria;
		return $this->collOnlines;
	}

	/**
	 * Returns the number of related Onlines.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      Connection $con
	 * @throws     PropelException
	 */
	public function countOnlines($criteria = null, $distinct = false, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseOnlinePeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		$criteria->add(OnlinePeer::PRODUCTION_ID, $this->getProductionId());

		return OnlinePeer::doCount($criteria, $distinct, $con);
	}

	/**
	 * Method called to associate a Online object to this object
	 * through the Online foreign key attribute
	 *
	 * @param      Online $l Online
	 * @return     void
	 * @throws     PropelException
	 */
	public function addOnline(Online $l)
	{
		$this->collOnlines[] = $l;
		$l->setProduction($this);
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Production is new, it will return
	 * an empty collection; or if this Production has previously
	 * been saved, it will retrieve related Onlines from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Production.
	 */
	public function getOnlinesJoinUser($criteria = null, $con = null)
	{
		// include the Peer class
		include_once 'src/model/whiteboard/om/BaseOnlinePeer.php';
		if ($criteria === null) {
			$criteria = new Criteria();
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOnlines === null) {
			if ($this->isNew()) {
				$this->collOnlines = array();
			} else {

				$criteria->add(OnlinePeer::PRODUCTION_ID, $this->getProductionId());

				$this->collOnlines = OnlinePeer::doSelectJoinUser($criteria, $con);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OnlinePeer::PRODUCTION_ID, $this->getProductionId());

			if (!isset($this->lastOnlineCriteria) || !$this->lastOnlineCriteria->equals($criteria)) {
				$this->collOnlines = OnlinePeer::doSelectJoinUser($criteria, $con);
			}
		}
		$this->lastOnlineCriteria = $criteria;

		return $this->collOnlines;
	}

} // BaseProduction
